### ISSUE TITLE
Failed to run sysbench prepare

### ISSUE THREAD

**Issue by ShahriyarR** [Percona-Lab/tokubackup-test#1]
```
$ tokubackuptest --prepare --defaults_file=/home/shahriyar.rzaev/AutoTokuBackp_Configs/tokubackuptest_ps_5.7_master.conf 
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_tokubackup/bin/tokubackuptest", line 11, in <module>
    load_entry_point('tokubackuptest==1.0', 'console_scripts', 'tokubackuptest')()
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_tokubackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_tokubackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_tokubackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_tokubackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_tokubackup/lib/python3.5/site-packages/tokubackuptest-1.0-py3.5.egg/tokubackuptest.py", line 28, in all_procedure
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_tokubackup/lib/python3.5/site-packages/tokubackuptest-1.0-py3.5.egg/tbtests/run_sysbench.py", line 28, in run_sysbench
  File "/home/shahriyar.rzaev/Python_interpreters/Python_3_5_3/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/home/shahriyar.rzaev/Python_interpreters/Python_3_5_3/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'sysbench  --test=/usr/share/doc/sysbench/tests/db/oltp.lua --oltp-test-mode=complex --num-threads=1000 --oltp-table-size=1000000 --mysql-db=dbtest  --mysql-user=msandbox --mysql-password=msandbox --db-driver=mysql  --max-requests=0  --mysql-socket=/home/shahriyar.rzaev/mytmp/mysql_sandbox20192.sock True'
```

**Comment by ShahriyarR** [comment]
It weird to have "True" at the end of the command

```
sysbench  --test=/usr/share/doc/sysbench/tests/db/oltp.lua --oltp-test-mode=complex \
--num-threads=1000 --oltp-table-size=1000000 --mysql-db=dbtest  \
--mysql-user=msandbox --mysql-password=msandbox --db-driver=mysql  \
--max-requests=0  \
--mysql-socket=/home/shahriyar.rzaev/mytmp/mysql_sandbox20192.sock True
```

**Comment by ShahriyarR** [comment]
The sysbench command seems to be fixed:

```
sysbench  --test=/usr/share/doc/sysbench/tests/db/oltp.lua --oltp-test-mode=complex \
--num-threads=1000 --oltp-table-size=1000000 --mysql-db=dbtest  --mysql-user=msandbox  \
--mysql-password=msandbox --db-driver=mysql  --max-requests=0  \
--mysql-socket=/home/shahriyar.rzaev/mytmp/mysql_sandbox20192.sock prepare
```

**Comment by ShahriyarR** [comment]
it seems to be work for "prepare"

```
$ tokubackuptest --prepare --defaults_file=/home/shahriyar.rzaev/AutoTokuBackp_Configs/tokubackuptest_ps_5.7_master.conf 
Database Created!
WARNING: the --test option is deprecated. You can pass a script name or path on the command line without any options.
WARNING: --num-threads is deprecated, use --threads instead
sysbench 1.0.2 (using bundled LuaJIT 2.1.0-beta2)

Creating table 'sbtest1'...
(py_3_5_3_tokubackup) [shahriyar.rzaev@qaserver-02 tokubackup-test]$ Inserting 1000000 records into 'sbtest1'

(py_3_5_3_tokubackup) [shahriyar.rzaev@qaserver-02 tokubackup-test]$ Creating secondary indexes on 'sbtest1'...
```
And for "run":

```
$ tokubackuptest --run --defaults_file=/home/shahriyar.rzaev/AutoTokuBackp_Configs/tokubackuptest_ps_5.7_master.conf 
WARNING: the --test option is deprecated. You can pass a script name or path on the command line without any options.
WARNING: --num-threads is deprecated, use --threads instead
sysbench 1.0.2 (using bundled LuaJIT 2.1.0-beta2)

Running the test with following options:
Number of threads: 1000
Initializing random number generator from current time


Initializing worker threads...
```

Not closing for now, need some more check
