### ISSUE TITLE
Implement running backup against slave servers while running sysbench on master

### ISSUE THREAD

**Issue by ShahriyarR** [Percona-Lab/tokubackup-test#12]
The scenarios is simple as:
1. Run sysbench against master server 
2. Run backup procedures against slave

**Comment by ShahriyarR** [comment]
The result:

```
$ tokubackuptest --prepare --backup --slave
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_tokubackup/bin/tokubackuptest", line 11, in <module>
    load_entry_point('tokubackuptest==1.0', 'console_scripts', 'tokubackuptest')()
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_tokubackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_tokubackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_tokubackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_tokubackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_tokubackup/lib/python3.5/site-packages/tokubackuptest-1.0-py3.5.egg/tokubackuptest.py", line 43, in all_procedure
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_tokubackup/lib/python3.5/site-packages/tokubackuptest-1.0-py3.5.egg/tbtests/run_sysbench.py", line 8, in __init__
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_tokubackup/lib/python3.5/site-packages/tokubackuptest-1.0-py3.5.egg/readconfig/config_reader.py", line 24, in __init__
  File "/home/shahriyar.rzaev/Python_interpreters/Python_3_5_3/lib/python3.5/configparser.py", line 956, in __getitem__
    raise KeyError(key)
KeyError: 'Slave'
```

**Comment by ShahriyarR** [comment]
The result after successful run:

```
$ tokubackuptest --prepare --backup --slave --defaults_file=/home/shahriyar.rzaev/AutoTokuBackup_Configs/tokubackuptest_ps_5.7_master.conf
/home/shahriyar.rzaev/percona-server/5.7.17/bin/mysql -umsandbox --password=msandbox --host=localhost --socket=/home/shahriyar.rzaev/mytmp/mysql_sandbox20192.sock -e "SELECT count(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'dbtest'"
The specified database already there!
Database Droppped!
Database Created!
sysbench 1.0.2 (using bundled LuaJIT 2.1.0-beta2)

Initializing worker threads...

Creating table 'sbtest1'...
Creating table 'sbtest2'...
Inserting 1000 records into 'sbtest1'
Inserting 1000 records into 'sbtest2'
Creating a secondary index on 'sbtest2'...
Creating a secondary index on 'sbtest1'...
WARN: starting backup process. This is not a multithreaded run, it is in loop
Something went wrong in run_backup(): 'BackupRun' object has no attribute 'mysql_slv'
Something went wrong in run_backup(): 'BackupRun' object has no attribute 'mysql_slv'
```
